version: '2'

services:
  webserver:
    image: nginx
    ports:
      - "82:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - fpm
  fpm:
    user: www-data
    build: ./docker/fpm
    volumes:
      - ./code:/var/www
    links:
      - db
  composer:
    image: composer
    volumes:
      - ./code:/app
  db:
    image: mysql:5.6
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server1
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
